### ISSUE TITLE
Support for asymmetric algo for signing token

### ISSUE THREAD

**Issue by skaglobal** [grails/grails-spring-security-rest#399]
The Plugin :2.0.0.RC1, does not support RS256 for signature encryption.
It only supports [HS256, HS384, HS512].

**Comment by alvarosanchez** [comment]
Pull requests are welcomed

**Comment by Trinition** [comment]
Jose4J's `DefaultJWSVerifierFactory` ([doc](https://www.javadoc.io/doc/com.nimbusds/nimbus-jose-jwt/4.0/com/nimbusds/jose/crypto/factories/DefaultJWSVerifierFactory.html), [source](https://github.com/felx/nimbus-jose-jwt/blob/master/src/main/java/com/nimbusds/jose/crypto/factories/DefaultJWSVerifierFactory.java)) might be a better solution to selecting the right verifier.

**Comment by jdaugherty** [comment]
The latest version of the project supports specifying this algorithm in `grails.plugin.springsecurity.rest.token.generation.jwt.algorithm` and is documented as supported by the `com.nimbusds.jose.JWSHeader` class.  I'm going to go ahead and close this as implemented.

**Comment by jdaugherty** [comment]
This is a dupe of https://github.com/grails/grails-spring-security-core/issues/1064
